#Example

Design the Vocabulary

Make a list of all of the words in our model vocabulary. The CountVectorizer provides a simple way to tokenize a collection of text documents and build a vocabulary of known words.

Create an instance of the CountVectorizer class.
Call the fit() function in order to learn a vocabulary from one or more documents.

Below is a snippet of the first few lines of text from the book A Tale of Two Cities by Charles Dickens.

It was the best of times

it was the worst of times,

it was the age of wisdom,

it was the age of foolishness

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
# Multiple documents
text = ["It was the best of times", "it was the worst of times", "it was the age of wisdom", "it was the age of foolishness"]
# create the transform
vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(text)
# summarize
print(sorted(vectorizer.vocabulary_))

['age', 'best', 'foolishness', 'it', 'of', 'the', 'times', 'was', 'wisdom', 'worst']


In [ ]:

print(vectorizer.vocabulary_)

{'it': 3, 'was': 7, 'the': 5, 'best': 1, 'of': 4, 'times': 6, 'worst': 9, 'age': 0, 'wisdom': 8, 'foolishness': 2}


In [ ]:
# encode document
vector = vectorizer.transform(text)
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

(4, 10)
[[0 1 0 1 1 1 1 1 0 0]
 [0 0 0 1 1 1 1 1 0 1]
 [1 0 0 1 1 1 0 1 1 0]
 [1 0 1 1 1 1 0 1 0 0]]


#Word2Vec

In [ ]:
#Word2Vec
import numpy as np
#numpy vektor ve matrısler uzerıne ıslem yapmamızı sağlar
from gensim.models import Word2Vec
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

In [ ]:
f = open('Alice.txt', 'r', encoding='utf8')
text = f.read()
t_list = text.split('\n')

corpus = []

for cumle in t_list:
    corpus.append(cumle.split())
print(corpus[:10])

[['\ufeffThe', 'Project', 'Gutenberg', 'eBook', 'of', 'Alice’s', 'Adventures', 'in', 'Wonderland,', 'by', 'Lewis', 'Carroll'], [], ['This', 'eBook', 'is', 'for', 'the', 'use', 'of', 'anyone', 'anywhere', 'in', 'the', 'United', 'States', 'and'], ['most', 'other', 'parts', 'of', 'the', 'world', 'at', 'no', 'cost', 'and', 'with', 'almost', 'no', 'restrictions'], ['whatsoever.', 'You', 'may', 'copy', 'it,', 'give', 'it', 'away', 'or', 're-use', 'it', 'under', 'the', 'terms'], ['of', 'the', 'Project', 'Gutenberg', 'License', 'included', 'with', 'this', 'eBook', 'or', 'online', 'at'], ['www.gutenberg.org.', 'If', 'you', 'are', 'not', 'located', 'in', 'the', 'United', 'States,', 'you'], ['will', 'have', 'to', 'check', 'the', 'laws', 'of', 'the', 'country', 'where', 'you', 'are', 'located', 'before'], ['using', 'this', 'eBook.'], []]


In [ ]:
model = Word2Vec(corpus, vector_size=100, window=5, min_count=1)
#Generally, a vector of 5-300 lengths is created for you #unsupervised learning method
#size 100 length vector
#window =Number of words to look up in window left and right
#sg 1 skip-gram will be used, cbow is used by default.
#mın_count at least how many times the word appears.
model.wv['Project']
# vw is the abbreviation for word vector
#word vector, word embedding, embedding always mean the same thing

array([ 7.70807788e-02,  2.88655549e-01, -1.16226152e-01,  1.24993615e-01,
        1.83777153e-01, -5.62934458e-01,  2.12668478e-01,  8.72455060e-01,
       -2.47146338e-01, -2.11463422e-01, -1.39254540e-01, -5.49603224e-01,
       -7.98113570e-02,  1.13490298e-01,  2.46273458e-01, -2.74360716e-01,
        3.53669897e-02, -4.20075774e-01, -1.74570307e-01, -7.31190085e-01,
        3.12023759e-01,  8.14186111e-02,  2.49995932e-01, -1.81752473e-01,
       -1.43132851e-01,  1.07910313e-01, -4.73924607e-01, -1.40482530e-01,
       -3.61049533e-01,  1.02604650e-01,  3.41766536e-01, -7.39720389e-02,
        1.32029891e-01, -3.15982223e-01, -3.21727805e-02,  4.46641445e-01,
        6.21003620e-02, -1.52634442e-01, -2.02028975e-01, -4.83841091e-01,
       -1.12192973e-01, -2.80626833e-01, -2.44684562e-01, -1.04985528e-01,
        3.22986096e-01, -1.13653354e-01, -3.27433437e-01, -1.02849215e-01,
        1.86474040e-01,  1.72396734e-01,  2.31077313e-01, -2.46972054e-01,
        2.11384725e-02, -

In [ ]:
print(model.wv.most_similar('Alice'))
#If the word you typed does not have a vocabulary, you will get an error.

[('and', 0.9998063445091248), ('a', 0.9997878670692444), ('the', 0.9997749328613281), ('in', 0.9997732639312744), ('her', 0.999764084815979), ('of', 0.9997384548187256), ('to', 0.9997365474700928), ('I', 0.9997336864471436), ('you', 0.9997313022613525), ('said', 0.9997237920761108)]


In [ ]:
#model.save('word2vec.model')
#model = Word2Vec.load('word2vec.model')

In [ ]:
# Print results
print("Cosine similarity between 'alice' " + "and 'wonderland' - CBOW : ", model.wv.similarity('Alice','Wonderland'))

print("Cosine similarity between 'alice' " + "and 'machines' - CBOW : ", model.wv.similarity('Alice', 'Adventures'))

Cosine similarity between 'alice' and 'wonderland' - CBOW :  0.9004052
Cosine similarity between 'alice' and 'machines' - CBOW :  0.96556467


In [ ]:
sgModel = Word2Vec(corpus, vector_size=100, window=5, min_count=1, sg=1)
#Generally, a vector of 5-300 lengths is created for you #unsupervised learning method
#size 100 length vector
#window =Number of words to look up in window left and right
#sg 1 skip-gram will be used, cbow is used by default.
#mın_count at least how many times the word appears.
sgModel.wv['Project']
# vw is the abbreviation for word vector
#word vector, word embedding, embedding always mean the same thing

array([ 0.02628078,  0.11854284, -0.16155481,  0.15424451,  0.14624324,
       -0.46668196,  0.15826827,  0.7803349 , -0.09153318, -0.24494389,
       -0.0999367 , -0.54088026,  0.04284949,  0.08686243,  0.1125246 ,
       -0.13905554,  0.13986744, -0.25294644, -0.00984014, -0.49829814,
        0.21089903,  0.00620985,  0.07050635, -0.25942615, -0.19010453,
        0.01556223, -0.41265172, -0.01733462, -0.20263217,  0.06438207,
        0.35817787, -0.08094802,  0.15868585, -0.34723303, -0.12895702,
        0.26435584,  0.0807356 , -0.14830439, -0.2748336 , -0.37446508,
       -0.10682103, -0.16359301, -0.25922403, -0.03900914,  0.2801009 ,
       -0.03600496, -0.2669862 , -0.13130069,  0.09543278,  0.07508913,
        0.11129457, -0.12963036,  0.1047076 , -0.1241993 , -0.02697697,
       -0.05540128,  0.17920646, -0.05039126, -0.17035042,  0.1196865 ,
        0.01086078, -0.0393079 , -0.06517751, -0.04598676, -0.26230687,
        0.2234855 ,  0.13109356,  0.1669057 , -0.38818628,  0.19

In [ ]:
# Print results
print("Cosine similarity between 'alice' " + "and 'wonderland' - Skip Gram : ", sgModel.wv.similarity('Alice','Wonderland'))

print("Cosine similarity between 'alice' " + "and 'machines' - Skip Gram : ", sgModel.wv.similarity('Alice', 'Adventures'))

Cosine similarity between 'alice' and 'wonderland' - SG :  0.9895322
Cosine similarity between 'alice' and 'machines' - SG :  0.99284714
